export const SET_TAB_POSITION = 'SET_TAB_POSITION';

export const BAR_ANCHOR_ELEMENT = 'BAR_ANCHOR_ELEMENT';

export const TOGGLE_FILTER_MENU = 'TOGGLE_FILTER_MENU';

export const TOGGLE_BUTTON_DISABLE = 'TOGGLE_BUTTON_DISABLE';

export const CHANGE_MENU_TITLE = 'CHANGE_MENU_TITLE';

export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';

// MAKE USER PAGE
export const SELECT_SYSTEM_TYPE = 'SELECT_SYSTEM_TYPE';
export const SELECT_VERSION = 'SELECT_VERSION';
export const SELECT_SERVER = 'SELECT_SERVER';
export const SHOW_VERSION = 'SHOW_VERSION';
export const SHOW_SERVER = 'SHOW_SERVER';
export const INPUT_KID = 'INPUT_KID';

// REGISTER USER PAGE
export const READY_FOR_UPLOAD = 'READY_FOR_UPLOAD';
export const MAKING_USER = 'MAKING_USER';

// USER LIST PAGE
export const SEARCH_KID_BY_KEYWORD = 'SEARCH_KID_BY_KEYWORD';

// USER DETAIL PAGE

// FETCH
export const FETCH_KIDS = 'FETCH_KIDS';
export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const FETCH_LICENSE = 'FETCH_LICENSE';
export const FETCH_FENICS = 'FETCH_FENICS';
export const FETCH_BUSIVS = 'FETCH_BUSIVS';
export const FETCH_HISTORYS = 'FETCH_HISTORYS';
export const FETCH_MEMOS = 'FETCH_MEMOS';
export const FETCH_MOBILES = 'FETCH_MOBILES';
export const FETCH_PATNERS = 'FETCH_PATNERS';
export const FETCH_SERVICES = 'FETCH_SERVICES';
export const FETCH_SERVERS = 'FETCH_SERVERS';
export const FETCH_MEMOTEMPLATES = 'FETCH_MEMOTEMPLATES';
export const FETCH_ACCOUNTS = 'FETCH_ACCOUNTS';
export const FETCH_ENVIRONMENTS = 'FETCH_ENVIRONMENTS';
export const FETCH_EVENTS = 'FETCH_EVENTS';

// FETCH RESULT
export const SUCCESSED_MAKE_USER = 'SUCCESSED_MAKE_USER';
export const FAILED_MAKE_USER = 'FAILED_MAKE_USER';
export const SUCCESSED_FETCH_KIDS = 'SUCCESSED_FETCH_KIDS';
export const FAILED_FETCH_KIDS = 'FAILED_FETCH_KIDS';
export const SUCCESSED_REGISTER_USER = 'SUCCESSED_REGISTER_USER';
export const FAILED_REGISTER_USER = 'FAILED_REGISTER_USER';

// POST
export const POST_MAKE_USER = 'POST_MAKE_USER';
export const POST_REGISTER_USER = 'POST_REGISTER_USER';
