export const SET_TAB_POSITION = 'SET_TAB_POSITION';

export const BAR_ANCHOR_ELEMENT = 'BAR_ANCHOR_ELEMENT';

export const TOGGLE_FILTER_MENU = 'TOGGLE_FILTER_MENU';

export const TOGGLE_BUTTON_DISABLE = 'TOGGLE_BUTTON_DISABLE';

export const CHANGE_MENU_TITLE = 'CHANGE_MENU_TITLE';
export const CHANGE_LOCATION = 'CHANGE_LOCATION';

export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';

// MAKE USER PAGE
export const SELECT_SYSTEM_TYPE = 'SELECT_SYSTEM_TYPE';
export const SELECT_VERSION = 'SELECT_VERSION';
export const SELECT_SERVER = 'SELECT_SERVER';
export const SHOW_VERSION = 'SHOW_VERSION';
export const SHOW_SERVER = 'SHOW_SERVER';
export const INPUT_KID = 'INPUT_KID';
export const TOGGLE_DIALOG = 'TOGGLE_DIALOG';

// REGISTER USER PAGE
export const READY_FOR_UPLOAD = 'READY_FOR_UPLOAD';
export const MAKING_USER = 'MAKING_USER';

// USER LIST PAGE
export const SEARCH_KID_BY_KEYWORD = 'SEARCH_KID_BY_KEYWORD';
export const FILTER_VERSION = 'FILTER_VERSION';
export const FILTER_NETWORK = 'FILTER_NETWORK';
export const FILTER_MOBILE = 'FILTER_MOBILE';
export const FILTER_SYSTEM_TYPE = 'FILTER_SYSTEM_TYPE';

// USER DETAIL PAGE
export const TOGGLE_EDIT_MODE = 'TOGGLE_EDIT_MODE';
export const TOGGLE_PREV_NEXT_BUTTON = 'TOGGLE_PREV_NEXT_BUTTON';
export const EDIT_CANCEL = 'EDIT_CANCEL';
export const CHANGE_BASEINFO_VALUE = 'CHANGE_BASEINFO_VALUE';
export const ADD_BASEINFO_VALUE = 'ADD_BASEINFO_VALUE';
export const CHANGE_CUSTOMER_VALUE = 'CHANGE_CUSTOMER_VALUE';
export const SELECT_BASE_INDEX = 'SELECT_BASE_INDEX';
export const SELECT_LICENSE = 'SELECT_LICENSE';
export const SELECT_CLIENT = 'SELECT_CLIENT';
export const CHANGE_NEWBASE_MODE = 'CHANGE_NEWBASE_MODE';
export const CHANGE_CLIENT_INFO = 'CHANGE_CLIENT_INFO';
export const SELECT_FENICS = 'SELECT_FENICS';
export const CHANGE_FENICS_INFO = 'CHANGE_FENICS_INFO';
export const TOGGLE_FENICS_DOWNLOAD_MODAL =
  'TOGGLE_FENICS_DOWNLOAD_MODAL';
export const TOGGLE_DOWNLOAD_ITEM = 'TOGGLE_DOWNLOAD_ITEM';
export const EXEC_FENICS_DOWNLOAD = 'EXEC_FENICS_DOWNLOAD';
export const SELECT_BUSIV_BASE_INDEX = 'SELECT_BUSIV_BASE_INDEX';
export const CHANGE_BUSIV_VALUE = 'CHANGE_BUSIV_VALUE';
export const TOGGLE_MEMO_MODAL = 'TOGGLE_MEMO_MODAL';
export const SELECT_MEMO_TEMPLATE = 'SELECT_MEMO_TEMPLATE';
export const CHANGE_MEMO_VALUE = 'CHANGE_MEMO_VALUE';
export const SELECT_MEMO = 'SELECT_MEMO';
export const CREATE_MEMO = 'CREATE_MEMO';
export const FILTER_MEMO = 'FILTER_MEMO';
export const SELECT_HISTORY = 'SELECT_HISTORY';
export const TOGGLE_DELETE_MODAL = 'TOGGLE_DELETE_MODAL';
export const FILTER_HISTORY = 'FILTER_HISTORY';

// FETCH
export const FETCH_KIDS = 'FETCH_KIDS';
export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const FETCH_LICENSE = 'FETCH_LICENSE';
export const FETCH_FENICS = 'FETCH_FENICS';
export const FETCH_BUSIVS = 'FETCH_BUSIVS';
export const FETCH_HISTORYS = 'FETCH_HISTORYS';
export const FETCH_MEMOS = 'FETCH_MEMOS';
export const FETCH_MOBILES = 'FETCH_MOBILES';
export const FETCH_PATNERS = 'FETCH_PATNERS';
export const FETCH_SERVICES = 'FETCH_SERVICES';
export const FETCH_SERVERS = 'FETCH_SERVERS';
export const FETCH_MEMOTEMPLATES = 'FETCH_MEMOTEMPLATES';
export const FETCH_ACCOUNTS = 'FETCH_ACCOUNTS';
export const FETCH_ENVIRONMENTS = 'FETCH_ENVIRONMENTS';
export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_USERINFO = 'FETCH_USERINFO';

// FETCH RESULT
export const SUCCESSED_MAKE_USER = 'SUCCESSED_MAKE_USER';
export const SUCCESSED_FETCH_KIDS = 'SUCCESSED_FETCH_KIDS';
export const SUCCESSED_REGISTER_USER = 'SUCCESSED_REGISTER_USER';
export const SUCCESSED_FETCH_SERVERS = 'SUCCESSED_FETCH_SERVERS';
export const SUCCESSED_FETCH_SERVICES =
  'SUCCESSED_FETCH_SERVICES';
export const SUCCESSED_FETCH_ENVIRONMENTS =
  'SUCCESSED_FETCH_ENVIRONMENTS';
export const SUCCESSED_FETCH_USERINFO =
  'SUCCESSED_FETCH_USERINFO';
export const SUCCESSED_FETCH_MEMOTEMPLATES =
  'SUCCESSED_FETCH_MEMOTEMPLATES';
export const FAILED_MAKE_USER = 'FAILED_MAKE_USER';
export const FAILED_FETCH_KIDS = 'FAILED_FETCH_KIDS';
export const FAILED_REGISTER_USER = 'FAILED_REGISTER_USER';
export const FAILED_FETCH_SERVERS = 'FAILED_FETCH_SERVERS';
export const FAILED_FETCH_SERVICES = 'FAILED_FETCH_SERVICES';
export const FAILED_FETCH_ENVIRONMENTS =
  'FAILED_FETCH_ENVIRONMENTS';
export const FAILED_FETCH_USERINFO = 'FAILED_FETCH_USERINFO';
export const FAILED_FETCH_MEMOTEMPLATES =
  'FAILED_FETCH_MEMOTEMPLATES';

// POST
export const POST_MAKE_USER = 'POST_MAKE_USER';
export const POST_REGISTER_USER = 'POST_REGISTER_USER';
