export const SET_TAB_POSITION = 'SET_TAB_POSITION';
export const BAR_ANCHOR_ELEMENT = 'BAR_ANCHOR_ELEMENT';
export const TOGGLE_FILTER_MENU = 'TOGGLE_FILTER_MENU';
export const TOGGLE_BUTTON_DISABLE = 'TOGGLE_BUTTON_DISABLE';
export const CHANGE_MENU_TITLE = 'CHANGE_MENU_TITLE';
export const CHANGE_LOCATION = 'CHANGE_LOCATION';
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';

// COMMON
export const TOGGLE_MODAL = 'TOGGLE_MODAL';

// MAKE USER PAGE
export const SELECT_SYSTEM_TYPE = 'SELECT_SYSTEM_TYPE';
export const SELECT_VERSION = 'SELECT_VERSION';
export const SELECT_SERVER = 'SELECT_SERVER';
export const SHOW_VERSION = 'SHOW_VERSION';
export const SHOW_SERVER = 'SHOW_SERVER';
export const INPUT_KID = 'INPUT_KID';
export const TOGGLE_DIALOG = 'TOGGLE_DIALOG';

// REGISTER USER PAGE
export const READY_FOR_UPLOAD = 'READY_FOR_UPLOAD';
export const MAKING_USER = 'MAKING_USER';

// USER LIST PAGE
export const CHANGE_USER_LIST_PAGE = 'CHANGE_USER_LIST_PAGE';
export const SEARCH_KID_BY_KEYWORD = 'SEARCH_KID_BY_KEYWORD';
export const FILTER_VERSION = 'FILTER_VERSION';
export const FILTER_NETWORK = 'FILTER_NETWORK';
export const FILTER_MOBILE = 'FILTER_MOBILE';
export const FILTER_SYSTEM_TYPE = 'FILTER_SYSTEM_TYPE';
export const FILTER_USER_LIST_BY_COLUMN =
  'FILTER_USER_LIST_BY_COLUMN';

// USER DETAIL PAGE
export const SELECT_USER = 'SELECT_USER';
export const TOGGLE_EDIT_MODE = 'TOGGLE_EDIT_MODE';
export const TOGGLE_PREV_NEXT_BUTTON = 'TOGGLE_PREV_NEXT_BUTTON';
export const EDIT_CANCEL = 'EDIT_CANCEL';
export const CHANGE_BASEINFO_VALUE = 'CHANGE_BASEINFO_VALUE';
export const ADD_BASEINFO_VALUE = 'ADD_BASEINFO_VALUE';
export const CHANGE_CUSTOMER_VALUE = 'CHANGE_CUSTOMER_VALUE';
export const SELECT_BASE_INDEX = 'SELECT_BASE_INDEX';
export const SELECT_LICENSE = 'SELECT_LICENSE';
export const SELECT_CLIENT = 'SELECT_CLIENT';
export const CHANGE_NEWBASE_MODE = 'CHANGE_NEWBASE_MODE';
export const CHANGE_CLIENT_INFO = 'CHANGE_CLIENT_INFO';
export const SELECT_FENICS = 'SELECT_FENICS';
export const CHANGE_FENICS_INFO = 'CHANGE_FENICS_INFO';
export const TOGGLE_FENICS_DOWNLOAD_MODAL =
  'TOGGLE_FENICS_DOWNLOAD_MODAL';
export const TOGGLE_DOWNLOAD_ITEM = 'TOGGLE_DOWNLOAD_ITEM';
export const EXEC_FENICS_DOWNLOAD = 'EXEC_FENICS_DOWNLOAD';
export const SELECT_BUSIV_BASE_INDEX = 'SELECT_BUSIV_BASE_INDEX';
export const CHANGE_BUSIV_VALUE = 'CHANGE_BUSIV_VALUE';
export const TOGGLE_MEMO_MODAL = 'TOGGLE_MEMO_MODAL';
export const SELECT_MEMO_TEMPLATE = 'SELECT_MEMO_TEMPLATE';
export const CHANGE_MEMO_VALUE = 'CHANGE_MEMO_VALUE';
export const SELECT_MEMO = 'SELECT_MEMO';
export const CREATE_MEMO = 'CREATE_MEMO';
export const FILTER_MEMO = 'FILTER_MEMO';
export const SELECT_HISTORY = 'SELECT_HISTORY';
export const TOGGLE_DELETE_MODAL = 'TOGGLE_DELETE_MODAL';
export const FILTER_HISTORY = 'FILTER_HISTORY';
export const TOGGLE_NEW_MEMOTEMPLATE_MODE =
  'TOGGLE_NEW_MEMOTEMPLATE_MODE';
export const SET_MEMO_TEMPLATE = 'SET_MEMO_TEMPLATE';
export const CHANGE_MEMO_TEMPLATE_VALUE =
  'CHANGE_MEMO_TEMPLATE_VALUE';
export const TOGGLE_TEMPLATE_DELETE_MODAL =
  'TOGGLE_TEMPLATE_DELETE_MODAL';
export const SELECT_SERVICE_VERSION = 'SELECT_SERVICE_VERSION';
export const CHANGE_PARTNER_VALUE = 'CHANGE_PARTNER_VALUE';

// SERVER
export const SELECT_PROJECT = 'SELECT_PROJECT';
export const TOGGLE_SERVER_EDIT_MODE = 'TOGGLE_SERVER_EDIT_MODE';
export const CHANGE_SERVER_VALUE = 'CHANGE_SERVER_VALUE';
export const SELECT_SERVERS = 'SELECT_SERVERS';
export const INPUT_SERVER_VALUE = 'INPUT_SERVER_VALUE';
export const TOGGLE_SERVER_CREATE_MODE = 'TOGGLE_SERVER_CREATE_MODE';

// SERVICE
export const EDIT_SERVICE = 'EDIT_SERVICE';
export const SELECT_SERVICE = 'SELECT_SERVICE';
export const TOGGLE_SERVICE_EDIT_MODE = 'TOGGLE_SERVICE_EDIT_MODE';
export const CHANGE_SERVICE_VALUE = 'CHANGE_SERVICE_VALUE';
export const TOGGLE_SERVICE_DELETE_MODAL =
  'TOGGLE_SERVICE_DELETE_MODAL';
export const INPUT_SERVICE = 'INPUT_SERVICE';

// GET
export const HTTP_GET = 'HTTP_GET';
export const HTTP_GET_SERVERS = 'HTTP_GET_SERVERS';
export const HTTP_GET_SERVICES = 'HTTP_GET_SERVICES';
export const HTTP_GET_MEMOTEMPLATES = 'HTTP_GET_MEMOTEMPLATES';
export const HTTP_GET_ACCOUNTS = 'HTTP_GET_ACCOUNTS';
export const HTTP_GET_ENVIRONMENTS = 'HTTP_GET_ENVIRONMENTS';
export const HTTP_GET_KIDS = 'HTTP_GET_KIDS';
export const FETCH_USERINFO = 'FETCH_USERINFO';

// POST
export const HTTP_POST = 'HTTP_POST';
export const POST_MAKE_USER = 'POST_MAKE_USER';
export const POST_REGISTER_USER = 'POST_REGISTER_USER';
export const POST_MEMO_TEMPLATE = 'POST_MEMO_TEMPLATE';
export const HTTP_POST_KIDS = 'HTTP_POST_KIDS';
export const HTTP_POST_CUSTOMERS = 'HTTP_POST_CUSTOMERS';
export const HTTP_POST_MEMOS = 'HTTP_POST_MEMOS';
export const HTTP_POST_SERVERS = 'HTTP_POST_SERVERS';
export const HTTP_POST_SERVICES = 'HTTP_POST_SERVICES';
export const HTTP_POST_MEMOTEMPLATES = 'HTTP_POST_MEMOTEMPLATES';
export const HTTP_POST_ACCOUNTS = 'HTTP_POST_ACCOUNTS';

// PUT
export const HTTP_PUT = 'HTTP_PUT';
export const HTTP_PUT_KIDS = 'HTTP_PUT_KIDS';
export const HTTP_PUT_CUSTOMERS = 'HTTP_PUT_CUSTOMERS';
export const HTTP_PUT_LICENSES = 'HTTP_PUT_LICENSES';
export const HTTP_PUT_CLIENTS = 'HTTP_PUT_CLIENTS';
export const HTTP_PUT_FENICSES = 'HTTP_PUT_FENICSES';
export const HTTP_PUT_BUSIVS = 'HTTP_PUT_BUSIVS';
export const HTTP_PUT_MOBILES = 'HTTP_PUT_MOBILES';
export const HTTP_PUT_PARTNERS = 'HTTP_PUT_PARTNERS';
export const HTTP_PUT_MEMOS = 'HTTP_PUT_MEMOS';
export const HTTP_PUT_SERVERS = 'HTTP_PUT_SERVERS';
export const HTTP_PUT_SERVICES = 'HTTP_PUT_SERVICES';
export const HTTP_PUT_ACCOUNTS = 'HTTP_PUT_ACCOUNTS';
export const HTTP_PUT_MEMOTEMPLATES = 'HTTP_PUT_MEMOTEMPLATES';

// DELETE
export const HTTP_DELETE = 'HTTP_DELETE';
export const HTTP_DELETE_SERVERS = 'HTTP_DELETE_SERVERS';
export const HTTP_DELETE_SERVICES = 'HTTP_DELETE_SERVICES';
export const HTTP_DELETE_MEMOTEMPLATES = 'HTTP_DELETE_MEMOTEMPLATES';
export const HTTP_DELETE_ACCOUNTS = 'HTTP_DELETE_ACCOUNTS';
export const HTTP_DELETE_KIDS = 'HTTP_DELETE_KIDS';
export const HTTP_DELETE_CUSTOMERS = 'HTTP_DELETE_CUSTOMERS';
export const HTTP_DELETE_CLIENTS = 'HTTP_DELETE_CLIENTS';
export const HTTP_DELETE_FENICSES = 'HTTP_DELETE_FENICSES';
export const HTTP_DELETE_HISTORYS = 'HTTP_DELETE_DELETE';
export const HTTP_DELETE_MEMOS = 'HTTP_DELETE_MEMOS';

// HTTP RESULT
export const SUCCESSED_HTTP_GET = 'SUCCESSED_HTTP_GET';
export const FAILED_HTTP_GET = 'FAILED_HTTP_GET';
export const SUCCESSED_MAKE_USER = 'SUCCESSED_MAKE_USER';
export const SUCCESSED_REGISTER_USER = 'SUCCESSED_REGISTER_USER';
export const SUCCESSED_FETCH_USERINFO = 'SUCCESSED_FETCH_USERINFO';

export const SUCCESSED_HTTP_POST = 'SUCCESSED_HTTP_POST';
export const FAILED_HTTP_POST = 'FAILED_HTTP_POST';

export const SUCCESSED_HTTP_PUT = 'SUCCESSED_HTTP_PUT';
export const FAILED_HTTP_PUT = 'FAILED_HTTP_PUT';

export const SUCCESSED_HTTP_DELETE = 'SUCCESSED_HTTP_DELETE';
export const FAILED_HTTP_DELETE = 'FAILED_HTTP_DELETE';
