declare type BusivLMType = {
  base_id: number,
  base_name: string,
  circuit_name: string,
  circuit_service: string,
  open_date: string,
  w_network: string,
  w_subnet: string,
  w_router: string,
  has_sx: NumberBool,
  how_to_cooperate: string,
  has_L3: NumberBool,
  sx_ip: string,
  has_carte: NumberBool,
  carte_system: string,
  carte_html_save_ip: string,
  has_cc: NumberBool,
  cc_ip: string,
  download_server_ip: string,
  auth_server_ip: string,
};
