declare type CustomerType = {
  kids_id: number,
  base_id: number,
  base_name: string | null,
  postal_cd: string | null,
  address: string | null,
  owner: string | null,
  affliation: string | null,
  tel: string | null,
  fax: string | null,
  email: string | null,
  has_busiv: NumberBool,
  has_fenics: NumberBool,
  has_mobile: NumberBool,
  is_new_contract: NumberBool,
  is_replaced_from_cj: NumberBool,
  is_replaced_from_wc: NumberBool,
  is_replaced_from_another: NumberBool,
};
