declare type StateType = {
  location: string,
  header: {
    title: string,
  },
  topPage: TopPageType,
  userMakePage: UserMakePageType,
  userRegisterPage: UserRegisterPageType,
  userListPage: UserListPageType,
  userDetailPage: UserDetailPageType,
  serverManagePage: ServerManagePageType,
  serviceManagePage: ServiceManagePageType,
  templateManagePage: TemplateManagePageType,
  partnerListPage: PartnerListPageType,
  fenicsListPage: FenicsListPageType,
  accountManagePage: AccountManagePageType,
  data: {
    kids: Array<KidType>,
    baseInfo: KidType,
    customers: Array<CustomerType>,
    clients: Array<ClientType>,
    fenics: Array<FenicsType>,
    busivs: Array<BusivType>,
    mobiles: Array<MobileType>,
    partners: Array<PartnerType>,
    historys: Array<HistoryType>,
    servers: Array<ServerType>,
    services: Array<ServiceType>,
    memos: Array<MemoType>,
  },
};
