declare type UserDetailPageType = {
  tabPosition: string,
  buttonPrevIsActive: boolean,
  buttonNextIsActive: boolean,
  isFetching: boolean,
  baseInfoTab: UserDetailTabBaseInfoType,
  customerTab: UserDetailTabCustomerType,
  clientTab: UserDetailTabClientType,
  fenicsTab: UserDetailTabFenicsType,
  busivTab: UserDetailTabBusivType,
  licenseTab: UserDetailTabLicenseType,
  partnerTab: UserDetailTabPartnerType,
  memo: UserDetailMemoType,
  historyTab: UserDetailTabHistoryType,
};
